[package]
name = "ez_netflow_cli"
version = "0.1.0"
edition = "2021"


[dependencies]
ez_netflow_lib = { path = "../ez_netflow_lib" }
rusqlite = { version = "0.33.0", features = ["bundled"] }
tabled = "0.17.0"